### ISSUE TITLE
dts: {{gender}} missing for some types and values undocumented

### ISSUE THREAD

**Issue by philcerf** [muckelba/poracleWiki#15]
At least monsters seem to support Genders, too, but that mentiones only {{genderData.emoji}}.

{{gender}} is quite handy, to test for 1 or 2 and only then print the actual emoji (cause having the genderless emoji is usually useless).

Also it would be nice to directly mention which value is what... it seems 0 = unset, 1 = male, 2 = female, 3 = genderless

**Comment by jfberry** [comment]
resolved
