### ISSUE TITLE
dts: would be nice to see some examples conditions etc.

### ISSUE THREAD

**Issue by philcerf** [muckelba/poracleWiki#17]
Hey.

AFAICS, there is little to no documentation in handlebars-helpers that tell how to do simple conditions, like
{{#is foo "bar"}}textA{{else}}textB{{/is}}.... or that one can nest these to create if/elsif.
Neither for how to use {{or}} and the like.

Would be nice to get some examples for that.

**Comment by jfberry** [comment]
dealt with in big wiki update (I think!)
