### ISSUE TITLE
commands: /track misses the PvP commands

### ISSUE THREAD

**Issue by philcerf** [muckelba/poracleWiki#19]
/track misses great, ultra, greatcp and ultracp.

It would also be nice to have some exta documentation, AFAIU, the following is the case (but better verify):
- greatN means, all ranks from 1 to N
- greatcpN means, at the maximum level (which is, AFAIU, here the "best" level for that kind of Pokemon, and not necessarily 50), it must have at least N CP.
- if greatcp/ultracp are omitted, a (admin-configurable) default is implicitly taken for them.

It should perhaps also explain, which Pokemon are displayed, which are AFAIU:
- all the evolutions, if their rank/CP match
- there is **not** one fix lvl for which all this is given (i.e. all assuming lvl50 or 40 or 51)... but rather just the rank,i.e. rank1 would be that combination of IV+level for which the stat-product of a given pokemon is the best. So there can be Pokemon, where the best stat-product is reached on e.g. 50,5 ... or any other level.
- if one tracks e.g. Bulbasaur... it will show the ranks for evolutions (e.g. bisaflor), ... but that tracking rule **won't** make it track Venusaur itself (i.e. a wild spawn).

**Comment by jfberry** [comment]
Resolved
