### ISSUE TITLE
commands: /raid boss-name vs. level vs. everything

### ISSUE THREAD

**Issue by philcerf** [muckelba/poracleWiki#22]
Hey.

There are 3 ways to select the bosses:
- the boss name (like Snorlax)
- raid level (which perhaps should be mentioned to have valid values 1-6)
- everything

AFAIU (and if so it should perhaps be mentioned):
- boss names and levels are stored separately,... i.e. tracking level1 won't add all level one bosses (which may anyway change their level) to the DB, but specifically "level1". Similarly, /raid remove level1 won't remove a manually added Snorlax (even if that was level1).
- everything, in add mode, works on levels (i.e. will simply add rules for 1-6),... on remove, right now it also works on levels only, but I think there is already a commit somewhere, which will make /raid remove everything also remove manually set Snorlax/etc.

**Comment by jfberry** [comment]
I think this is now resolved
