### ISSUE TITLE
commands: /invasion ... document the types

### ISSUE THREAD

**Issue by philcerf** [muckelba/poracleWiki#24]
AFAIU, the following types are accepted:
Bug, Dark, Dragon, Electric, Fairy, Fighting, Fire, Flying, Ghost, Grass, Ground, Ice, Metal, Normal, Poison, Psychic, Rock, Water, Mixed, Arlo, Cliff, Sierra, Decoy, Giovanni as well as everything.

But I have no idea whether especially Arlo, Cliff, Sierra, Decoy, Giovanni do work or not.
I think the maps cannot differentiate between decoys and Giovanni, or can they?

**Comment by jfberry** [comment]
Updated
