### ISSUE TITLE
dts field name changes with PR285

### ISSUE THREAD

**Issue by philcerf** [muckelba/poracleWiki#28]
With https://github.com/KartulUdus/PoracleJS/pull/285, numerous fields seem to have their names changed (at least the default dts was updated acordingly.

I remember:
- ivcolor -> ivColor
- mapurl -> googleMapUrl
- applemap -> appleMapUrl
- formname -> formName
- boostemoji -> boostWeatherEmoji
- quickMove -> quickMoveName
- chargeMove -> chargeMoveName
- staticmap -> staticMap
- pokestop_name -> pokestopName

I think there were more, ... it's probably best to compare the dts. from before and after the PR.

Further, several fields were newly added, ... and some were ether dropped (or just no longer used in the default dts.json).

Also, it seems there acually is a dfference between {{foo}} and {{{foo}}} ... and some fields that now use the triple version, still use the double version in the wiki.

**Comment by philcerf** [comment]
Oh and a number of options got added to local.json, too.

**Comment by jfberry** [comment]
dealt with in big wiki update (I think!)
